# Generated by Django 6.0.3 on 2026-03-13 19:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransicionFSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('INACTIVO', 'INACTIVO'), ('ACTIVO', 'ACTIVO'), ('ESCUCHANDO', 'ESCUCHANDO'), ('PROCESANDO', 'PROCESANDO'), ('RESPONDIENDO', 'RESPONDIENDO'), ('ERROR', 'ERROR'), ('DURMIENDO', 'DURMIENDO')], max_length=50)),
                ('evento', models.CharField(choices=[('EVT_NFC_ACTIVATE', 'EVT_NFC_ACTIVATE'), ('EVT_WAKEWORD', 'EVT_WAKEWORD'), ('EVT_PRESENCE_CONFIRMED', 'EVT_PRESENCE_CONFIRMED'), ('EVT_ATTENTION_GAINED', 'EVT_ATTENTION_GAINED'), ('EVT_SCHEDULE_TRIGGERED', 'EVT_SCHEDULE_TRIGGERED'), ('EVT_SPEECH_START', 'EVT_SPEECH_START'), ('EVT_ATTENTION_CONFIRMED', 'EVT_ATTENTION_CONFIRMED'), ('EVT_SPEECH_RECOGNIZED', 'EVT_SPEECH_RECOGNIZED'), ('EVT_GESTURE_COMMAND', 'EVT_GESTURE_COMMAND'), ('EVT_IDLE_TIMEOUT', 'EVT_IDLE_TIMEOUT'), ('EVT_ATTENTION_LOST', 'EVT_ATTENTION_LOST'), ('EVT_LISTEN_TIMEOUT', 'EVT_LISTEN_TIMEOUT'), ('EVT_MODULE_FAILURE', 'EVT_MODULE_FAILURE'), ('EVT_MIC_FAILURE', 'EVT_MIC_FAILURE'), ('EVT_PROCESS_FAILURE', 'EVT_PROCESS_FAILURE'), ('EVT_PROCESS_COMPLETED', 'EVT_PROCESS_COMPLETED'), ('EVT_RECOVERY_SUCCESS', 'EVT_RECOVERY_SUCCESS'), ('EVT_ERROR_RECOVERY_TIMEOUT', 'EVT_ERROR_RECOVERY_TIMEOUT'), ('CMD_FORCE_RESUME', 'CMD_FORCE_RESUME'), ('CMD_INHIBIR_ACTIVACION', 'CMD_INHIBIR_ACTIVACION'), ('CMD_INHIBIR_ESCUCHA', 'CMD_INHIBIR_ESCUCHA'), ('CMD_CANCEL_LISTENING', 'CMD_CANCEL_LISTENING'), ('EVT_SHUTDOWN', 'EVT_SHUTDOWN'), ('EVT_NFC_DEACTIVATE', 'EVT_NFC_DEACTIVATE')], max_length=50)),
                ('estado_nuevo', models.CharField(choices=[('INACTIVO', 'INACTIVO'), ('ACTIVO', 'ACTIVO'), ('ESCUCHANDO', 'ESCUCHANDO'), ('PROCESANDO', 'PROCESANDO'), ('RESPONDIENDO', 'RESPONDIENDO'), ('ERROR', 'ERROR'), ('DURMIENDO', 'DURMIENDO')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, help_text='Información contextual opcional del evento.', null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('is_guest', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
